name: flutter_katalog_sqlite
description: "Proyek Flutter Katalog dengan SQLite"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/laptop.jpg
    - assets/samsung.jpg
    - assets/smarttv.jpg
    - assets/sony.jpg